use aligned_vec::{AVec, ConstAlign, CACHELINE_ALIGN};

use crate::kd_tree::{ConstructionError, OwnedStemLeafResolution};
use crate::traits::leaf_strategy::ConstructibleLeafStrategy;
use crate::{Axis, Content, StemStrategy};

pub(super) trait ConstructionIndex: Copy + Send {
    fn from_usize(value: usize) -> Self;
    fn as_usize(self) -> usize;
}

impl ConstructionIndex for u32 {
    #[inline(always)]
    fn from_usize(value: usize) -> Self {
        value as u32
    }

    #[inline(always)]
    fn as_usize(self) -> usize {
        self as usize
    }
}

impl ConstructionIndex for usize {
    #[inline(always)]
    fn from_usize(value: usize) -> Self {
        value
    }

    #[inline(always)]
    fn as_usize(self) -> usize {
        self
    }
}

#[inline(always)]
pub(super) const fn construction_index_fits_u32(item_count: usize) -> bool {
    item_count <= u32::MAX as usize
}

pub(in crate::kd_tree) struct ConstructionLeafScratch<A, T, const K: usize> {
    pub(super) points: [Vec<A>; K],
    pub(super) items: Vec<T>,
    sort_order: Vec<usize>,
    original_at_position: Vec<usize>,
    position_of_original: Vec<usize>,
    sorter: Option<LeafSorter<A, T, K>>,
}

pub(in crate::kd_tree) type LeafSorter<A, T, const K: usize> =
    fn(&mut ConstructionLeafScratch<A, T, K>);

/// The summary `SHIFT`, `SS`, `K` and `B` generics are erased by this `fn`
/// pointer: the erased `SHIFT` is only recoverable through the builder's
/// `ITEM_LEAF_MODE` const generic. The invariant that a stored populator's
/// shift equals the builder's `ITEM_LEAF_MODE` is therefore enforced solely by
/// `enable_embedded_min_item_summary` — the only constructor that sets both —
/// not by the type system. Do not set `stem_summary_populator` anywhere else.
pub(in crate::kd_tree) type StemSummaryPopulator<A, LS> =
    fn(&mut AVec<A, ConstAlign<{ CACHELINE_ALIGN }>>, &LS, &OwnedStemLeafResolution, i32);

pub(in crate::kd_tree) fn sort_leaf_scratch_by_item<A, T: Ord, const K: usize>(
    scratch: &mut ConstructionLeafScratch<A, T, K>,
) {
    scratch.sort_order.clear();
    scratch.sort_order.extend(0..scratch.items.len());
    scratch
        .sort_order
        .sort_unstable_by(|&left, &right| scratch.items[left].cmp(&scratch.items[right]));

    scratch.original_at_position.clear();
    scratch.original_at_position.extend(0..scratch.items.len());
    scratch.position_of_original.clear();
    scratch.position_of_original.extend(0..scratch.items.len());

    for sorted_position in 0..scratch.items.len() {
        let desired_original = scratch.sort_order[sorted_position];
        let current_position = scratch.position_of_original[desired_original];
        if current_position == sorted_position {
            continue;
        }

        let displaced_original = scratch.original_at_position[sorted_position];
        scratch.items.swap(sorted_position, current_position);
        for axis in &mut scratch.points {
            axis.swap(sorted_position, current_position);
        }
        scratch
            .original_at_position
            .swap(sorted_position, current_position);
        scratch.position_of_original[desired_original] = sorted_position;
        scratch.position_of_original[displaced_original] = current_position;
    }
}

impl<A, T, const K: usize> ConstructionLeafScratch<A, T, K> {
    pub(super) fn with_capacity(capacity: usize, sorter: Option<LeafSorter<A, T, K>>) -> Self {
        let sort_capacity = if sorter.is_some() { capacity } else { 0 };
        Self {
            points: array_init::array_init(|_| Vec::with_capacity(capacity)),
            items: Vec::with_capacity(capacity),
            sort_order: Vec::with_capacity(sort_capacity),
            original_at_position: Vec::with_capacity(sort_capacity),
            position_of_original: Vec::with_capacity(sort_capacity),
            sorter,
        }
    }

    pub(super) fn sort_if_configured(&mut self) {
        if let Some(sorter) = self.sorter {
            sorter(self);
        }
    }

    pub(super) fn clear_and_reserve(&mut self, leaf_len: usize) {
        for axis in &mut self.points {
            axis.clear();
            if axis.capacity() < leaf_len {
                axis.reserve(leaf_len);
            }
        }
        self.items.clear();
        if self.items.capacity() < leaf_len {
            self.items.reserve(leaf_len);
        }
    }
}

pub(in crate::kd_tree) fn validate_auto_generated_items<T>(
    item_count: usize,
) -> Result<(), ConstructionError>
where
    T: TryFrom<usize>,
{
    if let Some(max_src_idx) = item_count.checked_sub(1) {
        if T::try_from(max_src_idx).is_err() {
            return Err(ConstructionError::AutoGeneratedItemIndexOverflow {
                item_count,
                item_type: core::any::type_name::<T>(),
            });
        }
    }

    Ok(())
}

pub(super) trait SoftConstructionMode<A, T, SS, LS, I, X, FA, FI, const K: usize, const B: usize>
where
    A: Axis<Coord = A>,
    T: Content,
    SS: StemStrategy,
    LS: ConstructibleLeafStrategy<A, T, SS, K, B>,
    I: ConstructionIndex,
    FA: Fn(&X, usize) -> A,
    FI: FnMut(usize, &X) -> Result<T, ConstructionError>,
{
    #[allow(clippy::too_many_arguments)]
    fn populate(
        &self,
        stems: &mut AVec<A, ConstAlign<{ CACHELINE_ALIGN }>>,
        source: &[X],
        axis_at: &FA,
        sort_index: &mut [I],
        root_stem_ordering: SS,
        max_stem_level: i32,
        leaf_budget: usize,
        leaves: &mut LS,
        actual_max_stem_level: &mut i32,
        max_leaf_len: &mut usize,
        leaf_scratch: &mut ConstructionLeafScratch<A, T, K>,
        item_at: &mut FI,
    ) -> Result<(), ConstructionError>;
}
